import { z } from "zod";
import { Id } from "./common.js";

/** A calendar date as the forms send it, e.g. 2026-09-29. */
export const IsoDate = z.iso.date();
const money = z.number().nonnegative().max(100_000_000);
const amount = z.number().nonnegative().max(10_000_000);
const text = (max: number) => z.string().trim().max(max).nullable().optional();

/** Where photos may live. Paths are generated by the API, so anything else is refused. */
export const PHOTO_FOLDERS = ["repairs", "fuel", "downtime"] as const;
export const PhotoPath = z
  .string()
  .regex(
    /^(repairs|fuel|downtime)\/[0-9a-f-]{36}\/[\w.-]{1,80}$/,
    "Not a photo this system stored",
  );
const photos = z.array(PhotoPath).max(10, "At most 10 photos").optional();

// ---------------------------------------------------------------- production logs

export const ProductionInput = z
  .object({
    mine_id: Id,
    date: IsoDate.optional(),
    shift: z.enum(["morning", "midday", "night"]).nullable().optional(),
    team_name: text(120),
    tons_produced: amount,
    magnetite_used: amount.optional(),
    magnetite_cost: money.optional(),
    overtime_hours: z
      .number()
      .nonnegative()
      .max(24 * 31)
      .optional(),
    overtime_cost: money.optional(),
    notes: text(1000),
  })
  .strict();
export const ProductionPatch = ProductionInput.partial().strict();
export type ProductionInput = z.infer<typeof ProductionInput>;
export type ProductionPatch = z.infer<typeof ProductionPatch>;
export const PRODUCTION_SORTABLE = ["date", "created_at", "tons_produced"] as const;

// ---------------------------------------------------------------- fuel slips

const fuelFields = {
  date: IsoDate.optional(),
  mine_id: Id.nullable().optional(),
  equipment_id: Id.nullable().optional(),
  vehicle_label: text(80),
  slip_no: text(40),
  fuel_type: z.enum(["diesel", "petrol", "oil", "other"]).optional(),
  litres: z.number().positive("Enter the litres pumped").max(100_000),
  cost_per_litre: z.number().nonnegative().max(1_000),
  odometer: z.number().nonnegative().nullable().optional(),
  hours_reading: z.number().nonnegative().nullable().optional(),
  employee_id: Id.nullable().optional(),
  notes: text(1000),
  photo_urls: photos,
};

/** `total_cost` is not accepted: the database works it out from litres and price. */
export const FuelInput = z
  .object(fuelFields)
  .strict()
  .refine((f) => !!f.equipment_id || !!f.vehicle_label?.trim(), {
    message: "Pick a vehicle or type a label",
    path: ["vehicle_label"],
  });
export const FuelPatch = z.object(fuelFields).partial().strict();
export type FuelInput = z.infer<typeof FuelInput>;
export type FuelPatch = z.infer<typeof FuelPatch>;
export const FUEL_SORTABLE = ["date", "created_at", "litres", "total_cost"] as const;

// ---------------------------------------------------------------- maintenance

export const MaintenancePartInput = z
  .object({
    stock_item_id: Id,
    qty: z.number().positive("Quantity must be more than zero").max(10_000),
    /** Leave out to use the stock item's current unit cost. */
    unit_cost: money.optional(),
  })
  .strict();
export type MaintenancePartInput = z.infer<typeof MaintenancePartInput>;

const maintenanceFields = {
  equipment_id: Id,
  date: IsoDate.optional(),
  description: z.string().trim().min(1, "Describe the repair").max(2000),
  labour_hours: z.number().nonnegative().max(1_000).optional(),
  labour_cost: money.optional(),
  downtime_hours: z.number().nonnegative().max(1_000).optional(),
  next_due_date: IsoDate.nullable().optional(),
  next_due_tons: amount.nullable().optional(),
  performed_by: text(120),
  photo_urls: photos,
};

/**
 * A repair and the parts it used, saved together. `parts_cost` and `total_cost` are not
 * accepted: the database works them out from the parts and the labour.
 */
export const MaintenanceInput = z
  .object({ ...maintenanceFields, parts: z.array(MaintenancePartInput).max(50).optional() })
  .strict();
/** Parts are changed through their own endpoints, so an update does not take them. */
export const MaintenancePatch = z.object(maintenanceFields).partial().strict();
export type MaintenanceInput = z.infer<typeof MaintenanceInput>;
export type MaintenancePatch = z.infer<typeof MaintenancePatch>;
export const MAINTENANCE_SORTABLE = ["date", "created_at", "total_cost"] as const;

// ---------------------------------------------------------------- stock usage and photos

export const StockUsageInput = z
  .object({
    stock_item_id: Id,
    qty: z.number().positive("Quantity must be more than zero").max(10_000),
  })
  .strict();
export type StockUsageInput = z.infer<typeof StockUsageInput>;

export const PhotoUploadInput = z
  .object({
    folder: z.enum(PHOTO_FOLDERS),
    content_type: z.enum(
      ["image/jpeg", "image/png", "image/webp"],
      "Only JPEG, PNG or WebP photos",
    ),
  })
  .strict();
export type PhotoUploadInput = z.infer<typeof PhotoUploadInput>;
